version: "3"

services:
    db:
        image: postgres:alpine
        restart: always
        volumes:
            - "${NEXTCLOUD_DATA}/db:/var/lib/postgresql/data:z"
        env_file:
            - .env

    redis:
        image: redis:alpine
        restart: always

    app:
        image: nextcloud:fpm-alpine
        restart: always
        volumes:
            # Основыныая папка NextCloud
            - "${NEXTCLOUD_DATA}/nextcloud:/var/www/html:z"
            # Папка с файлами
            - "${NEXTCLOUD_DATA}/nextcloud_data:/var/www/html/data:z"
        environment:
            - POSTGRES_HOST=db
            - REDIS_HOST=redis
        env_file:
            - .env
        depends_on:
            - db
            - redis

    web:
        build: ./web
        restart: always
        ports:
            - 8080:80
            - 443:443
        volumes:
            - "${NEXTCLOUD_DATA}/nextcloud:/var/www/html:z,ro"
            # Путь к вашему SSL-сертификату
            - "${NEXTCLOUD_DATA}/ssl/certificate.crt:/etc/ssl/certs/nginx.crt:ro"
            # Путь к вашему приватному ключу SSL-сертификата
            - "${NEXTCLOUD_DATA}/ssl/private_key:/etc/ssl/private/nginx.key:ro"
        depends_on:
            - app

    cron:
        image: nextcloud:fpm-alpine
        restart: always
        volumes:
            - "${NEXTCLOUD_DATA}/nextcloud:/var/www/html:z"
        entrypoint: /cron.sh
        depends_on:
            - db
            - redis
