version: "3"

services:
    db:
        image: mariadb:10.6
        restart: always
        command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
        volumes:
            - db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=nextcloud
            - MYSQL_USER=nextcloud
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}

    app:
        image: nextcloud:fpm
        restart: always
        links:
            - db
        depends_on:
            - db
        volumes:
            - nextcloud:/var/www/html
        environment:
            - MYSQL_HOST=db
            - MYSQL_DATABASE=nextcloud
            - MYSQL_USER=nextcloud
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}

    web:
        image: nginx
        restart: always
        ports:
            - 8080:80
        links:
            - app
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - nextcloud:/var/www/html

volumes:
    nextcloud:
    db:
