---
- name: Установка и настройка сервера NextClouduser
  hosts: all
  become: true
  vars:
      # INPUT - Пароль от базы данных
      POSTGRES_PASSWORD: "{{POSTGRES_PASSWORD}}"
      #
      #
      POSTGRES_USER: "nextcloud"
      POSTGRES_DB: "{{POSTGRES_USER}}"
      PATH_NEXTCLOUD: "/home/nextcloud"
  tasks:
      - name: Установка Docker
        import_tasks: ../../script/docker_install.yml

      - name: Копирование docker-compose на удаленный сервер
        synchronize:
            src: "../conf"
            dest: "{{PATH_NEXTCLOUD}}"
            delete: yes

      - name: Создание файла из шаблона
        template:
            src: db.j2
            dest: "{{PATH_NEXTCLOUD}}/conf/db.env"

      - name: docker-compose
        block:
            - name: Остановить docker-compose
              command: docker-compose down
              args:
                  chdir: "{{PATH_NEXTCLOUD}}/conf"

            - name: Запуск docker-compose
              command: docker-compose up -d
              args:
                  chdir: "{{PATH_NEXTCLOUD}}/conf"
